# Generated by Django 5.1.3 on 2024-11-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a book'), ('can_change_book', 'Can edit a book'), ('can_delete_book', 'Can delete a book')]},
        ),
    ]
